FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS publish
WORKDIR /src

COPY *.sln ./
COPY Api/Backend.Api.csproj ./
COPY Database/Backend.Database.csproj ./Database/

RUN dotnet restore ./Backend.Api.csproj

COPY . .
RUN dotnet publish "Backend.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false /p:EnableSourceLink=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS final
WORKDIR /app

RUN apk add --no-cache icu-libs

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

COPY --from=publish /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Backend.Api.dll"]
