// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Database.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    partial class BackendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Database.Entities.DerivedWord", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<Guid>("DerivedWordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId1")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntryId");

                    b.HasIndex("EntryId1");

                    b.ToTable("DerivedWord");
                });

            modelBuilder.Entity("Backend.Database.Entities.Entry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Categories")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text[]");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PosTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EntryId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Backend.Database.Entities.Proverb", b =>
                {
                    b.Property<Guid>("ProverbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DictionaryEntryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sense")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProverbId");

                    b.HasIndex("EntryId");

                    b.ToTable("Proverbs");
                });

            modelBuilder.Entity("Backend.Database.Entities.RelatedWord", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<Guid>("EntryId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedWordId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntryId");

                    b.HasIndex("EntryId1");

                    b.ToTable("RelatedWord");
                });

            modelBuilder.Entity("Backend.Database.Entities.Sense", b =>
                {
                    b.Property<Guid>("SenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DictionaryEntryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Glosses")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("RawTags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text[]");

                    b.HasKey("SenseId");

                    b.HasIndex("EntryId");

                    b.ToTable("Sense");
                });

            modelBuilder.Entity("Backend.Database.Entities.Synonym", b =>
                {
                    b.Property<Guid>("SynonymId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DictionaryEntryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("RawTags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text[]");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SynonymId");

                    b.HasIndex("EntryId");

                    b.ToTable("Synonyms");
                });

            modelBuilder.Entity("Backend.Database.Entities.Translation", b =>
                {
                    b.Property<Guid>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DictionaryEntryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Sense")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text[]");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TranslationId");

                    b.HasIndex("EntryId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("Backend.Database.Entities.WordRef", b =>
                {
                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasMaxLength(100)
                        .HasColumnType("text[]");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("WordRef");
                });

            modelBuilder.Entity("Backend.Database.Entities.DerivedWord", b =>
                {
                    b.HasOne("Backend.Database.Entities.Entry", "Entry")
                        .WithMany("DerivedWords")
                        .HasForeignKey("EntryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Backend.Database.Entities.Proverb", b =>
                {
                    b.HasOne("Backend.Database.Entities.Entry", "Entry")
                        .WithMany("Proverbs")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Backend.Database.Entities.RelatedWord", b =>
                {
                    b.HasOne("Backend.Database.Entities.Entry", "Entry")
                        .WithMany("RelatedWords")
                        .HasForeignKey("EntryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Backend.Database.Entities.Sense", b =>
                {
                    b.HasOne("Backend.Database.Entities.Entry", "Entry")
                        .WithMany("Senses")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Backend.Database.Entities.Synonym", b =>
                {
                    b.HasOne("Backend.Database.Entities.Entry", "Entry")
                        .WithMany("Synonyms")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Backend.Database.Entities.Translation", b =>
                {
                    b.HasOne("Backend.Database.Entities.Entry", "Entry")
                        .WithMany("Translations")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Backend.Database.Entities.Entry", b =>
                {
                    b.Navigation("DerivedWords");

                    b.Navigation("Proverbs");

                    b.Navigation("RelatedWords");

                    b.Navigation("Senses");

                    b.Navigation("Synonyms");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
